/**
 * Error types.
 * @author
 *
 */
public enum ErrorType {
	SUCCESS, 
	ACCESS_DENIED, 
	DOC_NOT_FOUND, 
	USER_NOT_FOUND, 
	REPO_NOT_FOUND, 
	USERNAME_ALREADY_EXISTS, 
	REPONAME_ALREADY_EXISTS,
	DOCNAME_ALREADY_EXISTS,
	NO_OLDER_VERSION, 
	REPO_NOT_SUBSCRIBED, 
	NO_PENDING_CHECKINS, 
	NO_LOCAL_CHANGES, 
	INTERNAL_ERROR,
	UNKNOWN_COMMAND
}